# fly.toml app configuration file generated for backend-green-water-3640 on 2024-08-10T10:03:26+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-green-water-3640'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 4444
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
